language: php
php:
  - 5.4
  - 5.5
  - 5.6


before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
  - composer install -n

script:
  - ./bin/phpunit
